import Book from "@/types/book";
export const books: Book[] = [
  {
    key: 1,
    image: "https://picsum.photos/200/300?random=1",
    summary:
      "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.",
    isbn: "978-1-56619-909-4",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishedDate: new Date("1925-04-10"),
    pageCount: 180,
    language: "English",
    publisher: "Charles Scribner's Sons",
  },
  {
    key: 2,
    image: "https://picsum.photos/200/300?random=2",
    summary:
      "Set in the racially charged atmosphere of the 1930s American South, To Kill a Mockingbird follows the experiences of young Scout Finch as she navigates the complexities of morality, justice, and prejudice. Narrated by Scout as an adult, the story centers around her father, Atticus Finch, a principled lawyer who defends Tom Robinson, a black man wrongly accused of raping a white woman. As the trial unfolds, Scout, along with her brother Jem and their friend Dill, grapple with the harsh realities of racism and inequality in their small town of Maycomb, Alabama. Through their innocent yet perceptive eyes, readers witness the deep-seated prejudices and social injustices that permeate society. Despite Atticus's valiant efforts to uphold truth and justice, Tom Robinson is convicted by an all-white jury, highlighting the pervasive racism of the time. The trial serves as a catalyst for Scout's moral awakening, as she learns valuable lessons about empathy, compassion, and the importance of standing up for what is right, even in the face of adversity. To Kill a Mockingbird is a timeless masterpiece that explores themes of innocence and experience, racial injustice, and the power of empathy. Harper Lee's poignant narrative and richly drawn characters continue to resonate with readers, challenging them to confront uncomfortable truths about society while inspiring hope for a more just and compassionate world.",
    isbn: "978-0-670-81364-5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishedDate: new Date("1960-07-11"),
    pageCount: 281,
    language: "English",
    publisher: "J. B. Lippincott & Co.",
  },

  {
    key: 3,
    isbn: "978-0-553-21399-7",
    summary:
      "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.r to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, y",
    image: "https://picsum.photos/200/300?random=3",
    title: "1984",
    author: "George Orwell",
    publishedDate: new Date("1949-06-08"),
    pageCount: 328,
    language: "English",
    publisher: "Secker & Warburg",
  },
  {
    key: 4,
    isbn: "978-0-140-27894-3",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall. and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a t",
    image: "https://picsum.photos/200/300?random=4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishedDate: new Date("1813-01-28"),
    pageCount: 279,
    language: "English",
    publisher: "T. Egerton, Whitehall",
  },
  {
    key: 5,
    isbn: "978-0-679-60132-9",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.or to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the Am",
    image: "https://picsum.photos/200/300?random=5",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    publishedDate: new Date("1967-05-30"),
    pageCount: 417,
    language: "Spanish",
    publisher: "Editorial Sudamericana",
  },
  {
    key: 6,
    isbn: "978-0-7432-7356-0",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall. Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a se",
    image: "https://picsum.photos/200/300?random=6",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishedDate: new Date("1951-07-16"),
    pageCount: 277,
    language: "English",
    publisher: "Little, Brown and Company",
  },
  {
    key: 7,
    isbn: "978-0-385-08223-7",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.n, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. G",
    image: "https://picsum.photos/200/300?random=7",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishedDate: new Date("1937-09-21"),
    pageCount: 310,
    language: "English",
    publisher: "Allen & Unwin",
  },
  {
    key: 8,
    isbn: "978-0-671-71173-2",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.s ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his",
    image: "https://picsum.photos/200/300?random=8",
    title: "Lord of the Flies",
    author: "William Golding",
    publishedDate: new Date("1954-09-17"),
    pageCount: 224,
    language: "English",
    publisher: "Faber and Faber",
  },
  {
    key: 9,
    isbn: "978-0-06-112008-4",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.",
    image: "https://picsum.photos/200/300?random=9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    publishedDate: new Date("1988-06-01"),
    pageCount: 197,
    language: "Portuguese",
    publisher: "Harper & Row",
  },
  {
    key: 10,
    isbn: "978-0-553-38249-2",
    summary: "Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.Set in the summer of 1922, The Great Gatsby paints a vivid portrait of the Jazz Age, a time of excess and decadence in America. The story is narrated by Nick Carraway, a young man from the Midwest who moves to Long Island, New York, to pursue a career in finance. Nick finds himself living next door to Jay Gatsby, a mysterious millionaire known for his lavish parties and extravagant lifestyle.As Nick becomes acquainted with Gatsby and his circle of acquaintances, he learns of Gatsby's obsessive love for Daisy Buchanan, Nick's cousin, who is married to the wealthy but morally bankrupt Tom Buchanan. Gatsby's entire existence revolves around winning Daisy back, despite the fact that their relationship ended years ago.Through a series of encounters and events, including lavish parties at Gatsby's mansion, clandestine meetings, and confrontations, Fitzgerald weaves a tale of love, betrayal, and tragedy. Gatsby's pursuit of Daisy symbolizes the American Dream, yet it ultimately leads to his downfall.",
    image: "https://picsum.photos/200/300?random=10",
    title: "The Shining",
    author: "Stephen King",
    publishedDate: new Date("1977-01-28"),
    pageCount: 447,
    language: "English",
    publisher: "Doubleday",
  },
];
